version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: project_db
    restart: unless-stopped

    environment:
      MONGO_INITDB_ROOT_USERNAME: project_user
      MONGO_INITDB_ROOT_PASSWORD: secure_password
      MONGO_INITDB_DATABASE: my_project_db

    volumes:
      - db_data:/data/db

    ports:
      - "27017:27017"
      
    networks:
      - app-network

  nodejs-backend:
    build:
      context: ./nodejs-backend
      dockerfile: Dockerfile
    container_name: project_backend
    restart: unless-stopped

    environment:
      DB_HOST: db
      DB_PORT: 27017
      DB_USER: project_user
      DB_PASSWORD: secure_password
      DB_NAME: my_project_db

    ports:
      - "8000:3000"

    volumes:
      - ./nodejs-backend:/usr/src/app
      - /usr/src/app/node_modules 

    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: project_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - nodejs-backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 

volumes:
  db_data:
    driver: local